

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?15," has no desirable effect."
	.GSTR STR?20,"You have lost your mind."
	.GSTR STR?74,"You haven't the strength.
"
	.GSTR STR?136,"Chestnut hair, tousled by the wind, frames the tanned oval of his face. "
	.GSTR STR?146,"""I wish you would call me 'Nicholas' -- I feel I know you much better than our brief acquaintance would allow."" He presses your hand"
	.GSTR STR?158,"Death lies that way, my lady."
	.GSTR STR?166,"A tall hedge prevents you from going around the east wing of the house."
	.GSTR STR?193," has a small pool of liquid at the bottom"
	.GSTR STR?225,"You hear metal scrape metal. A woman gasps."
	.GSTR STR?227,"You hear a piece of furniture being knocked over."
	.GSTR STR?230,"You hear a duellist leap forward, and swords clash, parrying."
	.GSTR STR?237,"PRSO"
	.GSTR STR?311,"   The tides are against you, however, and carry you out to sea. Days later you collapse, exhausted, to wake in the heaven on earth of a Swedish merchant marine. A midshipman, an ice-eyed blond with Viking physique and no English, nurses you back to health; in a moment of weakness you thank him in the only language all men and women share."
	.GSTR STR?86,".
"
	.GSTR STR?88,"Nothing happens.
"
	.GSTR STR?235,"Preaction"
	.GSTR STR?183,"A lace-covered table crouches beside a wing-backed chair in one corner."
	.GSTR STR?264,"sound"
	.GSTR STR?269,"Pulling"
	.GSTR STR?276,"pick"
	.GSTR STR?12,"

      ***   You have died   ***

"
	.GSTR STR?62,"rief descriptions.
"
	.GSTR STR?63,"   Lafond smacks you hard across the face with the back of his hand, ""Fool."" He casts aside all formalities."
	.GSTR STR?66,"Dragoons surround you. "
DRAGOONS-SURROUND=STR?66
	.GSTR STR?80,"He laughs triumphantly and pulls you into the dance.
"
	.GSTR STR?105,"""It's not safe down there,"" the Falcon calls."
	.GSTR STR?126,"With a creak and a crash, somewhere a mast falls to the deck"
	.GSTR STR?168,"Dragoons guard the gate."
	.GSTR STR?231,"Dragoons, conversing quietly, patrol the other side of the gate."
	.GSTR STR?239,"words"
	.GSTR STR?267,"with"
	.GSTR STR?341,"Dragoons surround you, appearing from nowhere. They show you no mercy, though they let you survive."
	.GSTR STR?8,"""Help me!"" you cry, hoping someone will help you."
	.GSTR STR?61,"It doesn't look like"
DOESNT-LOOK=STR?61
	.GSTR STR?87,"...

"
	.GSTR STR?266,"look inside"
	.GSTR STR?288,"Dagger sharpening"
	.GSTR STR?55," the edge of"
THE-EDGE=STR?55
	.GSTR STR?60," the dance floor"
DANCE-FLOOR=STR?60
	.GSTR STR?108,"You might be able to squeeze past it.
"
SQUEEZE-AROUND=STR?108
	.GSTR STR?156,"You might fight your way a few feet into the thorns but you'd only tear your clothes."
	.GSTR STR?244,"ends"
	.GSTR STR?313," and collapses.
   You were warned, of course, but did not listen. A stray keg pushes you off the deck into the sea."
	.GSTR STR?5,"Love Transcending Death"
	.GSTR STR?22,"That is a waste of time."
	.GSTR STR?25,"That seems a useless idea."
	.GSTR STR?39,"That is thoroughly unladylike behavior.
"
UNLADY=STR?39
	.GSTR STR?71,"That wouldn't be polite.
"
	.GSTR STR?93,"They already are.
"
ALREADY-ARE=STR?93
	.GSTR STR?171,"No expense has been spared to make this long dim hallway anything but a servant's corridor. The foyer is east, a kitchen north of you."
	.GSTR STR?214,"They calls me Andy, but I'm really randy"
	.GSTR STR?252,"drop"
	.GSTR STR?308," Lafond's dragoons deal with you quickly."
	.GSTR STR?327,"They clamp shut"
	.GSTR STR?340,". Visiting that Neptune you tol' me about. Gone to sea, poor man,"" he laughs, and returns to lurking around the doorway."
	.GSTR STR?16,"Think again, guv'nor."
	.GSTR STR?51,"You'll have to "
	.GSTR STR?57,"The ballroom is a "
	.GSTR STR?134,"You'll have to row that way."
	.GSTR STR?149,"The blue of the captain's eyes seems to deepen, looking at you"
	.GSTR STR?248,"Biting"
	.GSTR STR?294,"wear"
	.GSTR STR?295,"posi"
	.GSTR STR?296,"remove"
	.GSTR STR?297," Suddenly, an offshore current pulls you past the reefs into the open sea. You haven't the strength to row back."
	.GSTR STR?304,"finely woven"
	.GSTR STR?17,"This is no time to get hysterical."
	.GSTR STR?21,"What an odd thing to attempt."
	.GSTR STR?43,"You pace out the steps.
"
PACE=STR?43
	.GSTR STR?53,"You pull the cloth aside momentarily."
	.GSTR STR?94," do you want to "
DO-YOU-WANT=STR?94
	.GSTR STR?99,"This reveals nothing new.
"
	.GSTR STR?109,"This is a gloomy, damp area at the bottom of the Helena Louise. To the fore there seems to be a little more light, or you can climb up some steep stairs."
	.GSTR STR?120,"This tiny kitchen smells of old stew and yeast. A low door to starboard shows the way out."
	.GSTR STR?121,"You perch on a platform high above the deck, giving a view of the endless sea and the southernmost cliffs of the island, where a house pokes out of the vegetation. It gives off a general glow, but no lights can be seen in any of the second story windows. A tiny beach nestles into the base of the cliff."
	.GSTR STR?142,"What the devil are you doing here! Lafond is a dangerous man to play with!"" Jamison "
	.GSTR STR?176,"The carpeted hallway turns from west to north here, extending into the east wing. A long table blocks the way south."
	.GSTR STR?178,"Lit only with moonlight through the open window, tonight this room is serving as a ladies' dressing room. An exit lies to the north."
	.GSTR STR?180,"This room is exotically furnished with a Turkey divan and chairs. The exit is south."
	.GSTR STR?201,"This tiny cell is airless and shivering cold, entirely empty of anything but darkness. A wooden door leads west."
	.GSTR STR?204,"This short passage turns from east to north to stop abruptly at an iron door."
	.GSTR STR?242,"talk to characters."
	.GSTR STR?243,"begins"
	.GSTR STR?263,"Knocking on"
	.GSTR STR?290,"talk to"
	.GSTR STR?299,"be holding"
	.GSTR STR?107,"The door at the top of the stairs won't open."
	.GSTR STR?115,"The door is barred."
	.GSTR STR?249,"blow"
	.GSTR STR?328,"The door creaks open to reveal a black well, water hushing deep within"
	.GSTR STR?30,"Completely common looking "
	.GSTR STR?127,"You recognize a voice from far away, ""Don't take that! Look in the cabin at the stern -- you'll find some fun there!"" It sounds like Davis"
	.GSTR STR?153,"A bench is built into the wall, circling the folly."
	.GSTR STR?3,"You shake your head"
SHAKE-HEAD=STR?3
	.GSTR STR?76,"A sinewy arm encircles you, ""Stay, my lady."""
	.GSTR STR?103,"A bit of canvas sail "
	.GSTR STR?135,"You stop at a steep cliff-face."
	.GSTR STR?165,"The front door stands open to the south, light splayed out onto a drive stretching north into the jungle. A path leads around the western wing of the house; jutting out from the east wing is a tall hedge."
	.GSTR STR?179,"You stand in a carpeted hallway, leading east to a stair landing. Rooms lie north and south of you."
	.GSTR STR?182,"You stand in a carpeted hallway, leading west to a stair landing. To the north is an ornately carved door. From the south comes the impression of light and air."
	.GSTR STR?188,"You stare into space for a long, thoughtless moment. It seems very hard to think, you think, but you aren't sure."
	.GSTR STR?210,"You squeeze three colorless drops "
	.GSTR STR?218,"Ye're a tasty doxy to let slip, but no 'elp fer it."
	.GSTR STR?232,"Not Here"
	.GSTR STR?323,"You sweep down into the ballroom, felling dancer and pirate alike. Unfortunately, one of Jamison's crew, mistaking your shortcut for an attack, greets you with a sharpened dagger."
	.GSTR STR?9,"mutters something to himself. You hear an occasional ""Zounds!"""
	.GSTR STR?77," squeeze through the opening between cupboard and wall"
	.GSTR STR?89,"Failed.
"
	.GSTR STR?119,"The grate is too small."
	.GSTR STR?125,"""The Falcon! The Falcon conquers!"" yells someone"
	.GSTR STR?247,"ask"
	.GSTR STR?42,"You're not holding"
	.GSTR STR?58,"You're already "
	.GSTR STR?70,"That's not done in polite society.
"
	.GSTR STR?83,"You're holding it!
"
	.GSTR STR?98," calls after you.

"
CALLS-AFTER=STR?98
	.GSTR STR?154,"One bamboo slat at the back seems to be loose."
	.GSTR STR?196,"A strong wet breeze blows from a low doorway to the east. A circle of light leads west. The passageway continues south."
	.GSTR STR?219,"Out of the smoke staggers Davis, tugging a bloodied knife from the back of a pirate. Davis's eyes gleam white from a face blackened and bloody, his lips dark red as if he has been drinking blood. He turns to face you."
	.GSTR STR?260,"look"
	.GSTR STR?281,"to"
	.GSTR STR?79,"Look around you.
"
	.GSTR STR?95,"But it's such a beautiful night!
"
	.GSTR STR?124,"""Cap'n Jamison! We've got 'em!"" cries a rough voice"
	.GSTR STR?223,", shrugging off your lack of cooperation"
	.GSTR STR?301,"   It's been rather a long time since any of the crew have dealt with the fairer sex, and they are a bit rough, despite Rodney Quick's exhortations."
	.GSTR STR?329,". You are pulled struggling into the pool."
	.GSTR STR?65,"Something cracks over your head, knocking you unconscious.
   You awaken, cuddled in a huge purple and gold curtained bed, with a shocking migraine. The man lying next to you pays no heed to your complaints, and commands you in French when you try to defend yourself. He tires of you within a few weeks, but lets you work the streets of Santa Ananas."
	.GSTR STR?110,"A grate blocks your way."
	.GSTR STR?172,"A grandiose staircase splits and twists up to the next floor here, framing the entrance south to the ballroom. Long hallways lead east and west; cool night air drifts in through the front door, north of you."
	.GSTR STR?278,"Pushing"
	.GSTR STR?101,"A plank of wood "
	.GSTR STR?192," is brimming with wine"
	.GSTR STR?31," only darkness beyond"
	.GSTR STR?33," is closed"
	.GSTR STR?54," only the back of"
	.GSTR STR?97," walks up to you. ""M. Lafond requests your presence in his room immediately, Miss."" He points "
	.GSTR STR?113,"A dagger is driven into the wooden floorboards."
	.GSTR STR?207,"Draped across the bed is a lovely cream colored watered silk gown. It looks about your size."
	.GSTR STR?233,"Actor"
	.GSTR STR?312,"A large one rolls into you, stumbling you through the railing into the sea."
	.GSTR STR?68,"PLUNDERED HEARTS"
	.GSTR STR?202,"The monster lunges at you, chain rattling, roaring and angry. "
	.GSTR STR?139,"""We have anchored off St. Sinistra,"" says Captain Jamison, ""and I must look like a guest at Lafond's dance tonight. I will find and free your father, and then finally wreak my revenge on Lafond."" He half draws his rapier from its scabbard."
	.GSTR STR?206,"Kicked into a far corner is a pile of clothes."
	.GSTR STR?250,"get into"
	.GSTR STR?275,"light"
	.GSTR STR?283,"get in"
	.GSTR STR?300,"stand up"
	.GSTR STR?18,"It's Bedlam for you!"
	.GSTR STR?24,"It's not worth it. Believe me."
	.GSTR STR?29," A tangled mass of rigging hangs down from the mast, like many rope ladders woven together."
	.GSTR STR?36,"It's too dark to see a thing."
	.GSTR STR?41," halfway up the cliff stairs."
	.GSTR STR?216,"What, afrighted of a lick o' the whip?"
	.GSTR STR?229,"Rapiers click and slide. ""Bad parry, Captain,"" Lafond says."
	.GSTR STR?11,"enters just a few steps behind you."
	.GSTR STR?137,"The pirate captain "
	.GSTR STR?152,"Perfumed by the heady odor of the night-blooming jasmine entwined in the bamboo latticework, this folly is a cool, dark haven."
	.GSTR STR?167,"A rutted drive runs north-south here, from a high spiked gate through the jungle to Lafond's mansion. You hide in the bushes nearby."
	.GSTR STR?256,"close"
	.GSTR STR?284,"search"
	.GSTR STR?326,"put anything into"
	.GSTR STR?334,"dainty fists"
	.GSTR STR?343,"The pistol fires with a deafening roar, spraying shot into Nicholas. Time stops as he falls, reaching for you, your name his last breath.
   The battle afterwards is short and bloody. Spurred by grief, you fight hard, yet greet benumbing death thankfully."
	.GSTR STR?254,"climb into"
	.GSTR STR?255,"climb onto"
	.GSTR STR?265,"open"
	.GSTR STR?270,"move"
	.GSTR STR?48,"way to do that.
"
	.GSTR STR?56,"To your surprise, "
SURPRISE=STR?56
	.GSTR STR?129,"The reefs seem a little larger than you thought before"
	.GSTR STR?130,"The reefs are definitely getting larger"
	.GSTR STR?147,"Jamison touches your hair softly"
	.GSTR STR?148,"Jamison grins down at you, a dazzling white smile"
	.GSTR STR?151,"Nicholas's hands are smooth and cool"
	.GSTR STR?175,"One long table set across the north entrance indicates that supper was served here earlier. West of you is the ballroom."
	.GSTR STR?222,", his wig awry, sprawls across the parquet floor."
LAF-MUNGED=STR?222
	.GSTR STR?234,"M-Beg"
	.GSTR STR?240,"letters"
	.GSTR STR?262,"Kicking"
	.GSTR STR?286,"Shaking"
	.GSTR STR?316,"Nicholas stops at your cry, and turns, curious, to face Crulley just as the pistol sprays shot into his chest."
	.GSTR STR?14," accomplishes nothing."
	.GSTR STR?128,"The ship is floating midway between the island and a line of reefs"
	.GSTR STR?133,"The sound of splintering wood reverberates through the ship as it drifts onto the reefs"
	.GSTR STR?159,"The steps lead south."
	.GSTR STR?220,"He kisses your forehead.
"
	.GSTR STR?337,"The study of Latin"
	.GSTR STR?37,"Although the lagoon is warm and clear, it is much too deep.
"
TOO-DEEP=STR?37
	.GSTR STR?44,"There's nothing "
	.GSTR STR?102,"Some bloodied flesh "
	.GSTR STR?140,"""I am sorry you have been confined down here, but I don't trust my lonely crew with such beauty. Crulley isn't the only man aboard with few principles."" He smiles at you, eyes lingering, and takes your hand. You feel your color rising. ""If anything goes wrong, turn to Cookie. He is quite deaf, but capable. He'll see you through."""
	.GSTR STR?215,"Would yer like a taste o' water?"
	.GSTR STR?251,"get onto"
	.GSTR STR?253,"burn"
	.GSTR STR?298,"get on"
	.GSTR STR?303,"get off"
	.GSTR STR?310,"get out of"
	.GSTR STR?106,"The Falcon follows a step behind."
	.GSTR STR?161,"The undergrowth is much too thick to enter."
	.GSTR STR?169,"The underbrush is much too thick to enter."
	.GSTR STR?181,"A pair of duelling pistols is mounted high on one wall."
	.GSTR STR?306,"   Suddenly you appreciate what it is to be a ball in an exploding cannon. The intense heat, the push of fire, and the sense of release when spit from the cannon's mouth -- these you feel when the lighted fuse finally burns up to the largest keg of gunpowder in the hold."
	.GSTR STR?338,"steal jewelry"
	.GSTR STR?28," drips off your fingers.
"
	.GSTR STR?32,"He doesn't respond.
"
	.GSTR STR?170,"A firepit in the floor smokes badly, fogging up the depths of this large kitchen, somehow not escaping through either the south or west doors."
	.GSTR STR?241,"AGAIN"
	.GSTR STR?280,"read"
	.GSTR STR?282,"return it to"
	.GSTR STR?317,"As you fiddle with the"
	.GSTR STR?333,"As you lift the hat from its"
	.GSTR STR?38," is not flush against the doorsill. "
	.GSTR STR?131,"Bswish! Waves smash against the reefs nearby"
	.GSTR STR?164,"The west wall of the house is that way."
	.GSTR STR?174,"The windows overlooking the veranda do not open."
	.GSTR STR?177," Cookie harrumphs, surprised."
	.GSTR STR?198,"Once a cell, now, with the door missing, made into a guard's bunkroom, this room is distinctly uncomfortable. Gasps of air are forced through a crack in the seaward wall of the room. The way out is west of you."
	.GSTR STR?258,"drink"
	.GSTR STR?259,"drink from"
	.GSTR STR?279,"Playing in this way with"
	.GSTR STR?10,"follows you."
	.GSTR STR?112,"An eerie battle cry arises on the wind, from all sides of the house"
	.GSTR STR?185,"'s eyes are getting heavier"
	.GSTR STR?186," collapses, head back, snoring loudly"
	.GSTR STR?191," is ornate and expensive"
	.GSTR STR?224,"Swords engage and disengage."
	.GSTR STR?245,"leave the game"
	.GSTR STR?257,"have hysterics"
	.GSTR STR?289,"Swimming"
	.GSTR STR?291,"do that to"
	.GSTR STR?150,"His eyes twinkle, like moonlight on the sea"
	.GSTR STR?228,"""You must ... pay ... for your actions!"" Nicholas gasps."
	.GSTR STR?331,"on"
	.GSTR STR?143," With an engaging smile he bows and leaves the folly.
"
	.GSTR STR?144,"""I haven't found your father. We've long suspected a passage under the library, but I cannot find an entrance,"" says Jamison"
	.GSTR STR?195,"Flickering torchlight lights the bottom of a spiral staircase. A draft blows from the east; a passage leads south."
	.GSTR STR?261,"Fiddling with"
	.GSTR STR?271,"Trying to destroy"
	.GSTR STR?272,"Trying to muzzle"
	.GSTR STR?309,"Firing cannon"
	.GSTR STR?315,"launch"
	.GSTR STR?116,"If you wish to go to the Poop, go AFT."
	.GSTR STR?184," seems to be having some problems stifling a yawn"
	.GSTR STR?190,"Sleep overtakes you and you slump into unconsiousness."
	.GSTR STR?318,"   Roaring anger and revenge, Lafond runs in, pouncing upon you. Your death, when it comes, is wished for."
	.GSTR STR?45,"It seems that"
	.GSTR STR?34,"Steep stairs descend "
	.GSTR STR?211,"Stunned, Crulley collapses at your feet, his eyes rolling"
	.GSTR STR?2," his eyes rake over your inadequately dressed body, the damp chemise clinging to your legs and heaving bosom, your gleaming hair"
	.GSTR STR?7,"Happily Ever After"
	.GSTR STR?40,"It is thoroughly unladylike to "
	.GSTR STR?78,"Suicide is not the answer.
"
	.GSTR STR?141,"His look darkens. ""You should know why I hate Lafond: Some years ago, as my brother and his bride sailed to a new life in Virginia, pirates struck. Their ship was boarded, looted and burned, the women taken, never to be seen again. A sailor, the one survivor, watched as a man of Lafond's description shot my brother in the back as he tried to save the women. Lafond has now bought respectability, but he shall never buy peace."" Jamison straightens resolutely, bows, and departs."
	.GSTR STR?145,"""If there is any trouble, and I am unable to help -- a signal from an upstairs seaward window will bring my men. They can be here in moments,"" the Captain says"
	.GSTR STR?187,"Your face convulses in a prodigious yawn."
	.GSTR STR?189,"Your eyes are extraordinarily dry. You blink to moisten them, and snort awake a minute later, drool dripping down your chin."
	.GSTR STR?277,"pour"
	.GSTR STR?285,"Turning"
	.GSTR STR?302,"Your battered hands can take no more. Your grip loosens and the sea comes up to break your fall."
	.GSTR STR?69,"[Press RETURN or ENTER to "
	.GSTR STR?73,"Sorry, no loitering,"" says the butler"
	.GSTR STR?274,"extinguish"
	.GSTR STR?292,"Caressing"
	.GSTR STR?6,"Pirate Queen"
	.GSTR STR?35,"A tiny glow of fire creeps across a stretch of floor -- inside the cage full of ammunition"
	.GSTR STR?162,"Buried in the subtropical undergrowth, you lose all sense of being on someone's private estate; jungle seems to extend for miles on all sides of you. A footworn path curves from east to north here, and the vegetation lessens to the northeast."
	.GSTR STR?213,"Avast me, but ain't ye a beauty"
	.GSTR STR?217,"Leave yer honey be, wench. He'll join ye anon."
	.GSTR STR?273,"nega"
	.GSTR STR?332,"put"
	.GSTR STR?335,"slippered toes"
	.GSTR STR?19,"Don't be absurd."
	.GSTR STR?23,"Don't dally around."
	.GSTR STR?26,"Don't bother."
	.GSTR STR?50,"You aren't "
	.GSTR STR?52,"You already have"
	.GSTR STR?84,"[There seems to be a noun missing in that sentence.]
"
	.GSTR STR?91,"Pardon?
"
	.GSTR STR?92,"It already is.
"
	.GSTR STR?100,"[There was no verb in that sentence!]
"
	.GSTR STR?104,"You are in an officer's cabin, lit by the firelight glowing through a porthole. A door is to starboard. Except for the built-in bed, the room seems to have been emptied thoroughly, if hurriedly."
	.GSTR STR?117,"Cannon line the deck, aimed at open sea and the island."
	.GSTR STR?122,"Don't push your luck too far."
	.GSTR STR?132,"You are misted in the spray of waves hitting the reefs. The island is far away"
	.GSTR STR?160,"You are on a well-trampled lawn at the side of the house, one low doorway leading in to the east. Gravelled paths lead north and south into the undergrowth."
	.GSTR STR?163,"You are in a small clearing under the western side of the house. Heavy vines creep up the wall past a second floor window, open to the night air. Southwest is an opening in the bushes."
	.GSTR STR?200,"You are at the far end of a dank passageway heading north. A wooden door leads east."
	.GSTR STR?209,"A small bottle has been dropped nearby."
	.GSTR STR?293,"in front of"
	.GSTR STR?320,"You awake too late to save the ship -- or rather, you never wake at all."
	.GSTR STR?322,"Startled, Lafond raises his sword and you fly onto the blade. You fall over your lover's body and expire, your lips on his in a kiss outlasting death."
	.GSTR STR?324,"Other cries rise to match yours as you sweep down the center of the ballroom in an avalanche of dancers, knocking yourself unconscious against the far wall. You awaken the next morning, in the village, embarrassed and alone."
	.GSTR STR?330,"put the stone in"
	.GSTR STR?111,"A chipped piece of mirror sits propped on a shoulder-high timber."
	.GSTR STR?118,". ""Hey, boy! Get away from those. It ain't safe!"" yells a sailor."
	.GSTR STR?173,""" The butler points up the stairs.
"
	.GSTR STR?236,"PRSI"
	.GSTR STR?238,"OOPS"
	.GSTR STR?1,"You can't go that way."
	.GSTR STR?46,"You can see"
	.GSTR STR?47,"You can't see any "
	.GSTR STR?49,"You can't "
	.GSTR STR?81,"You can't do that from here.
"
	.GSTR STR?82,"You can't go that way.
"
	.GSTR STR?85,"   "
	.GSTR STR?114,"You can't swim, and decide not to jump."
	.GSTR STR?155,"You crouch in the green rustlings of the hedge. Not far east, wind keens up the cliff, high above swells breaking against a rocky shore. You know the folly is somewhere to the west. North, the hedge is somewhat less dense."
	.GSTR STR?157,"You can't see any way to get past into the folly."
	.GSTR STR?194,"Cool salt air, blowing past a torch on a spiral staircase below you, ruffles your hair and circles south into the library."
	.GSTR STR?246,"restart"
	.GSTR STR?4,"Orphan"
	.GSTR STR?27,"You dip the oars and pull them towards you. The "
	.GSTR STR?59," over the head with"
	.GSTR STR?96," over your white linen chemise. Mama would say you belonged in a brothel.
"
	.GSTR STR?138,"Eyes closed, his skin with the pallor of death, Nick looks entirely spent.
"
	.GSTR STR?197,"A canvas cot is shoved against a wall."
	.GSTR STR?203,". The monster snorts in its sleep"
	.GSTR STR?208,". There is a tear at the bottom"
TEAR=STR?208
	.GSTR STR?212,"Me name's Andy Crulley, and ladies learn to love me"
	.GSTR STR?221,"Lafond grabs your hair and pulls your head sharply back, clinching your arms to your sides. "
	.GSTR STR?226,"Lafond's voice is cold, lazy, ""You will die, you know, Jamison."""
	.GSTR STR?314,". The next few minutes last forever as havoc breaks out. Grabbing a plank, you manage to stay afloat, but you are washed out to sea. A brig, Portuguese by its sails, rescues you. The sailors are brown skinned and smooth, and the first mate, the ship's and yours, is gentle. They leave you in Rio, alone and forgotten."
	.GSTR STR?321,". The governor of St. Sinistra provides you with food and shelter; at least, until he grows tired of your body and your presence."
	.GSTR STR?336,"Lafond hits you back. The end is not sweet and not fast."
	.GSTR STR?339,"Lafond pulls the sheets up to cover you both, pressing his long flaccid body against yours. Waves crash against the base of the cliff."
	.GSTR STR?342,"Lafond cries, ""No deal then. Take them, men!"" The dragoons pour down the cliff."
	.GSTR STR?64," The fall to the bottom of the well is endless; you've lost consciousness by the time the water overtakes you."
	.GSTR STR?75,", pushing you out of the house.
"
	.GSTR STR?90,"Aye-aye.
"
	.GSTR STR?268,"marrying"
	.GSTR STR?287,"soak"
	.GSTR STR?307," The blade bites less then you expected."
	.GSTR STR?319,"Too drugged to keep your grip on the ropes, you slip into the sea."
	.GSTR STR?13," doesn't do anything."
	.GSTR STR?67,"You find yourself speechless with dread.
"
	.GSTR STR?123,"""Aaieeee!"" echoes a scream, followed by several grunts and thumps"
	.GSTR STR?205,"Hewn from dense rock, the cell is a stagnant burrow. Except for the tiniest glow of light from the torch two rooms away, it is pitch black."
	.GSTR STR?325,"untie it"
	.GSTR STR?72,"Mama would have been shocked.
"
	.GSTR STR?199,"A powder horn hangs on a long strap from the wall."
	.GSTR STR?305,"thick"

	.ENDI
